defmodule Puppies.BreedsAttributes do

  alias Puppies.Breeds

  def update_breeds do
    Enum.each(attributes(), fn breed ->
      b = Puppies.Breeds.get_breed_by_name(breed.name)
      Breeds.update_breed(b, breed)
    end)
  end

  def attributes() do
   [
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 5, name: "Yorkshire Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 2, attention_and_exercise: 4, name: "Whoodle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Wirehaired Pointing Griffon"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Whippet"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Westiepoo"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Xoloitzcuintli"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Yorkipoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Yakutian Laika"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "West Highland White Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Welsh Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Weimaraner"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Welsh Springer Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Valley Bulldog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Treeing Walker Coonhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Vizsla"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Treeing Tennessee Brindle"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Transylvanian Hound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Toy Fox Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Tibetan Spaniel"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 5, name: "Tibetan Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Tibetan Mastiff"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Thai Ridgeback"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Texas Heeler"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Terripoo"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Taiwan Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Swedish Lapphund"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Swedish Vallhund"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 2, name: "Sussex Spaniel"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Standard Schnauzer"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Staffordshire Bull Terrier"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 2, attention_and_exercise: 2, name: "Staffy Bull Bullmastiff"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Stabyhoun"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Springador"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 2, attention_and_exercise: 3, name: "Spanish Mastiff"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Soft Coated Wheaten Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Small Munsterlander Pointer"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Spinone Italiano"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Sloughi"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Skye Terrier"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Silky Terrier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Silken Windhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Siberian Husky"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Shollie"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Shorkie"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Shiloh Shepherd"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Shikoku"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 2, attention_and_exercise: 3, name: "Shiranian"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Shih Tzu"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Shih-Poo"},
    %{adaptable: 4, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Shiba Inu"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Shepsky"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Sheepadoodle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Shetland Sheepdog"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 2, attention_and_exercise: 4, name: "Shichon"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Sealyham Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Scottish Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Scottish Deerhound"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Schipperke"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Schnoodle"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Saluki"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Samoyed"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 2, attention_and_exercise: 3, name: "Saint Bernard"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Saint Berdoodle"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Samusky"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Rottweiler"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Redbone Coonhound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Rottador"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Rhodesian Ridgeback"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Rat Terrier"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Pyrenean Mastiff"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 5, name: "Pyrenean Shepherd"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Rottle"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Pyredoodle"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Pugalier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Puli"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Pudelpointer"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Puggle"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 2, attention_and_exercise: 4, name: "Pug"},
    %{adaptable: 4, friendly: 3, grooming_and_health: 3, trainable: 2, attention_and_exercise: 3, name: "Puginese"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Portuguese Water Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Portuguese Sheepdog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Poochon"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Poodle"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Pomsky"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Portuguese Podengo Pequeno"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Portuguese Pointer"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Pomeranian"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Pomeagle"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Pomchi"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Pomapoo"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Pitsky"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Polish Lowland Sheepdog"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Plott"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Pharaoh Hound"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "Pointer"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Pocket Beagle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Petit Basset Griffon Vendéen"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 4, attention_and_exercise: 2, name: "Pekingese"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 5, name: "Papipoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Papillon"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Pembroke Welsh Corgi"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Otterhound"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Peekapoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Patterdale Terrier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Old English Sheepdog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Norwich Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Norwegian Lundehund"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Nova Scotia Duck Tolling Retriever"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Norwegian Elkhound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Norwegian Buhund"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Norfolk Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Northern Inuit Dog"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 3, name: "Newfoundland"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 2, attention_and_exercise: 3, name: "Neapolitan Mastiff"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Mudi"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Mutt (Mixed)"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Mountain Feist"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Mountain Cur"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Morkie"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Miniature Schnauzer"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Miniature Pinscher"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 2, attention_and_exercise: 4, name: "Maremma Sheepdog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Mastador"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Manchester Terrier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Maltipoo"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 2, attention_and_exercise: 4, name: "Mastiff"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Maltese Shih Tzu"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Maltese"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Lowchen"},
    %{adaptable: 4, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Lhasa Apso"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Leonberger"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Lakeland Terrier"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Lancashire Heeler"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Lhasapoo"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Lagotto Romagnolo"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Labsky"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Labrastaff"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Labmaraner"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Labrabull"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Labradane"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Labernese"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Labradoodle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Labrador Retriever"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Lab Pointer"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Kyi-Leo"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Kooikerhondje"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 4, trainable: 2, attention_and_exercise: 4, name: "Kuvasz"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Kishu Ken"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Kerry Blue Terrier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "King Shepherd"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Komondor"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Keeshond"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Karelian Bear Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Korean Jindo Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Japanese Spitz"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 2, name: "Japanese Chin"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 5, attention_and_exercise: 4, name: "Jackshund"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Jack Russell Terrier"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Kai Ken"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Jack Chi"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Jack-A-Poo"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Italian Greyhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Irish Water Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Irish Red And White Setter"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Icelandic Sheepdog"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "Irish Setter"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Irish Terrier"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Irish Wolfhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Ibizan Hound"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Huskita"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 2, attention_and_exercise: 4, name: "Hovawart"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Horgi"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Hokkaido"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Havapoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Huskydoodle"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Havanese"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Harrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Hanoverian Scenthound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 5, trainable: 4, attention_and_exercise: 4, name: "Greyador"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Hamiltonstovare"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 5, trainable: 4, attention_and_exercise: 4, name: "Greyhound"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Great Dane"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Great Pyrenees"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Greater Swiss Mountain Dog"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Gordon Setter"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Gollie"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Goldendoodle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Golden Shepherd"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Golden Cocker Retriever"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Golden Retriever Corgi"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Golden Retriever"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Golden Mountain Dog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Goldador"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Goberian"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "German Wirehaired Pointer"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "German Shorthaired Pointer"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Glen of Imaal Terrier"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Giant Schnauzer"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "German Spitz"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "German Sheprador"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "German Shepherd Rottweiler Mix"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "German Pinscher"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "German Longhaired Pointer"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Frengle"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "German Shepherd Pit Bull"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "German Shepherd Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "French Spaniel"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Frenchton"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "French Bullhuahua"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "French Bulldog"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Finnish Spitz"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 5, name: "Fox Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Flat-Coated Retriever"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Finnish Lapphund"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Field Spaniel"},
    %{adaptable: 2, friendly: 2, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Fila Brasileiro"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 2, attention_and_exercise: 3, name: "Eurasier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Estrela Mountain Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Entlebucher Mountain Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "English Toy Spaniel"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "English Setter"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "English Foxhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "English Springer Spaniel"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "English Cocker Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Dutch Shepherd"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Drever"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Doxle"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Doxiepoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 2, name: "Dorkie"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Dogue de Bordeaux"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Drentsche Patrijshond"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Dorgi"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Dogo Argentino"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Doberdor"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Doberman Pinscher"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Deutscher Wachtelhund"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Danish-Swedish Farmdog"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Docker"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Dandie Dinmont Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Daniff"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Dalmatian"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Corgidor"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Dachshund"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Curly-Coated Retriever"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Coton de Tulear"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Corman Shepherd"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Croatian Sheepdog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Dachsador"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Corgi Inu"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Collie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Cirneco dell’Etna"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chusky"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Cocker Spaniel"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 3, name: "Clumber Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Cockalier"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Cockapoo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chug"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chipin"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chiweenie"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Chion"},
    %{adaptable: 3, friendly: 1, grooming_and_health: 3, trainable: 2, attention_and_exercise: 2, name: "Chow Chow"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Chinook"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Chow Shepherd"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 3, trainable: 3, attention_and_exercise: 2, name: "Chinese Shar-Pei"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Chorkie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chigi"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chilier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Chi-Poo"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 3, name: "Chihuahua"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Chi Chi"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 2, name: "Chinese Crested"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Chesapeake Bay Retriever"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Cheagle"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Chabrador"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Central Asian Shepherd Dog"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Cavapoo"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Cavalier King Charles Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Cavador"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Cavachon"},
    %{adaptable: 4, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Cesky Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Cav-a-Jack"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Catahoula Bulldog"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Carolina Dog"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Catahoula Leopard Dog"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 3, name: "Cardigan Welsh Corgi"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Caucasian Shepherd Dog"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Cane Corso"},
    %{adaptable: 4, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Canaan Dog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Cairn Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Bullmastiff"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 2, attention_and_exercise: 3, name: "Bulldog"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bullmatian"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Bullador"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Bullboxer Pit"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Bull Terrier"},
    %{adaptable: 2, friendly: 2, grooming_and_health: 4, trainable: 2, attention_and_exercise: 2, name: "Bull-Pei"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bull Arab"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Brussels Griffon"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Broholmer"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Brittany"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 4, attention_and_exercise: 4, name: "Briard"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Bugg"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Braque du Bourbonnais"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bracco Italiano"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Boykin Spaniel"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Boxmatian"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Boxador"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Boxer"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Boxerdoodle"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Boxweiler"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bouvier des Flandres"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 5, name: "Boston Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Boston Terrier Pekingese Mix"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Bossie"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 2, attention_and_exercise: 3, name: "BoShih"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Bordoodle"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 2, name: "Borzoi"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Boston Boxer"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Border Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Border Sheepdog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Border Collie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bohemian Shepherd"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Bolognese"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Borador"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Boglen Terrier"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Boerboel"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 3, trainable: 5, attention_and_exercise: 4, name: "Bocker"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Bluetick Coonhound"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "Blue Lacy"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Black Mouth Cur"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Bloodhound"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Black Russian Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Black and Tan Coonhound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Biewer Terrier"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Bichon Frise"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Bernese Mountain Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Bernedoodle"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 5, name: "Berger Picard"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Belgian Tervuren"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Bergamasco Sheepdog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Belgian Sheepdog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Belgian Malinois"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Belgian Laekenois"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Bedlington Terrier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Bearded Collie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Beabull"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Beaglier"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Beagle"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Basset Retriever"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Bavarian Mountain Scent Hound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 2, name: "Basset Hound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Basset Fauve de Bretagne"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Bassador"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Azawakh"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Barbet"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 2, trainable: 4, attention_and_exercise: 3, name: "Basenji"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Australian Stumpy Tail Cattle Dog"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Australian Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 4, name: "Australian Shepherd Pit Bull Mix"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Australian Shepherd Lab Mix"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Australian Shepherd Husky"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 5, attention_and_exercise: 4, name: "Australian Kelpie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Australian Retriever"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 2, trainable: 5, attention_and_exercise: 5, name: "Australian Shepherd"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Australian Cattle Dog"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "Aussiedoodle"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Auggie"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Aussiepom"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Appenzeller Sennenhunde"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Anatolian Shepherd Dog"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "American Staffordshire Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "American Water Spaniel"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "American Pugabull"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "American Pit Bull Terrier"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "American Leopard Hound"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "American Hairless Terrier"},
    %{adaptable: 2, friendly: 5, grooming_and_health: 4, trainable: 4, attention_and_exercise: 5, name: "American Foxhound"},
    %{adaptable: 3, friendly: 5, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "American English Coonhound"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "American Bulldog"},
    %{adaptable: 4, friendly: 5, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "American Eskimo Dog"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 4, attention_and_exercise: 5, name: "Alaskan Malamute"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Alaskan Klee Kai"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Akita Shepherd"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 4, trainable: 3, attention_and_exercise: 3, name: "Akita Pit"},
    %{adaptable: 3, friendly: 1, grooming_and_health: 3, trainable: 3, attention_and_exercise: 4, name: "Akita Chow"},
    %{adaptable: 3, friendly: 4, grooming_and_health: 4, trainable: 3, attention_and_exercise: 2, name: "Akbash"},
    %{adaptable: 3, friendly: 2, grooming_and_health: 4, trainable: 4, attention_and_exercise: 4, name: "Akita"},
    %{adaptable: 2, friendly: 4, grooming_and_health: 3, trainable: 5, attention_and_exercise: 5, name: "Airedale Terrier"},
    %{adaptable: 4, friendly: 4, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Afghan Hound"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 2, trainable: 3, attention_and_exercise: 4, name: "Affenpinscher"},
    %{adaptable: 3, friendly: 3, grooming_and_health: 3, trainable: 3, attention_and_exercise: 3, name: "Affenhuahua"},
    %{adaptable: 2, friendly: 3, grooming_and_health: 3, trainable: 4, attention_and_exercise: 4, name: "Afador"},
    ]
  end
end

Puppies.BreedsAttributes.update_breeds()
