import Config

# Configure your database
config :puppies, Puppies.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "puppies_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :puppies, PuppiesWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NxssHAjhn1H3pdJWohM/Idi43g4RSuFvQCfDWezcdmPQiFp9byUb7Dq7Rv18id+H",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :puppies, PuppiesWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/puppies_web/(live|views)/.*(ex)$",
      ~r"lib/puppies_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

import Config

config :puppies,
  mapbox_key:
    "pk.eyJ1IjoicXVpYnN0YXIiLCJhIjoiY2p0Z2swbTg1MGwxeTQzcGRkaGVuanZtbCJ9.MWATWztvdPMOhAAv24c78w",
  cognito_api_Key: "sandbox_key_f0509c0192c780a6505681d057546b07",
  cognito_api_secret:
    "sandbox_secret_9d58f096f2cd42bc7bc0b92c51143b6e4b5244bba26507fc942104d11fba7f2c",
  elasticsearch_base_url: "http://localhost:9200",
  the_captain_base_url: "https://the-captain-java-staging.herokuapp.com/v3",
  the_captain_api_key: "tbd",
  ip_stack_api_key: "tbd",
  twilio_account_sid: "tbd",
  twilio_auth_token: "tbd",
  twilio_service: "tbd"

config :stripity_stripe,
  api_key: "tbd",
  publishable_key: "tbd",
  signing_secret: "tbd"

config :ex_aws,
  debug_requests: true,
  access_key_id: "tbd",
  secret_access_key: "tbd",
  s3: [
    scheme: "https://",
    host: "reputable-rooms-staging.s3.amazonaws.com",
    region: "us-east-1"
  ]

config :puppies, ReputableRooms.Mailer, adapter: Swoosh.Adapters.Local
